# Generated by Django 5.2.1 on 2025-05-18 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_alter_category_image_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='drop_banners/')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='upcoming', max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='DropProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('initial_stock_quantity', models.PositiveIntegerField(default=0)),
                ('current_stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('max_per_customer', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_products', to='drops.drop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_drops', to='products.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_drops', to='products.productvariant')),
            ],            options={
                'ordering': ['-is_featured', 'product__name'],
                'constraints': [models.CheckConstraint(check=models.Q(('current_stock_quantity__gte', 0)), name='check_current_stock_non_negative'), models.CheckConstraint(check=models.Q(('current_stock_quantity__lte', models.F('initial_stock_quantity'))), name='check_current_stock_lte_initial')],
                'unique_together': {('drop', 'product', 'variant')},
            },
        ),
    ]
