# Generated by Django 5.2.1 on 2025-05-28 12:03

import drops.utils
import products.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, storage=products.storage.CloudflareR2Storage(), upload_to=drops.utils.drop_banner_image_path),
        ),
    ]
