# Generated by Django 5.2.1 on 2025-05-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency_code',
            field=models.CharField(default='BYN', max_length=3),
        ),
    ]
