# Generated by Django 5.2.1 on 2025-06-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_payment_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency_code',
            field=models.CharField(default='USD', max_length=3),
        ),
    ]
