# Generated by Django 5.2.1 on 2025-06-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_alter_drop_banner_image'),
        ('orders', '0003_alter_payment_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='drop_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='drops.dropproduct'),
        ),
    ]
