# Generated by Django 5.2.1 on 2025-05-18 12:12

import products.models
import products.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_category_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=products.storage.CloudflareR2Storage(), upload_to=products.models.category_image_path),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=products.storage.CloudflareR2Storage(), upload_to=products.models.general_product_image_path),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=products.storage.CloudflareR2Storage(), upload_to=products.models.product_variant_image_path),
        ),
    ]
