# Generated by Django 5.2.1 on 2025-06-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buy_now_link',
            field=models.URLField(blank=True, help_text='External payment link for Buy Now functionality', max_length=500, null=True),
        ),
    ]
