# Generated by Django 5.2.1 on 2025-06-15 09:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_is_arch_e4b8a9_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_categor_7c5b12_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_base_pr_d9f8e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_name_8a2c41_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_slug_6e7d9a_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='products_ca_is_acti_b19b49_idx',
            old_name='products_ca_is_acti_0f7c98_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='products_ca_parent__ff262a_idx',
            old_name='products_ca_parent__44b8f2_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='products_ca_slug_da4386_idx',
            old_name='products_ca_slug_fb2c72_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='products_pr_product_48d699_idx',
            old_name='products_pr_product_2c8b94_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='products_pr_variant_e006ea_idx',
            old_name='products_pr_variant_5d7a63_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='products_pr_is_prim_b891de_idx',
            old_name='products_pr_is_prim_4f9c82_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_product_66459e_idx',
            old_name='products_pr_product_3b9f82_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_size_id_b5e26d_idx',
            old_name='products_pr_size_id_a7c4d1_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='products_pr_is_acti_b10163_idx',
            old_name='products_pr_is_acti_7f3e85_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, db_index=True, default=list, size=None),
        ),
    ]
