# Generated by Django 5.2.1 on 2025-05-28 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cartitem_unique_together_cartitem_color_and_more'),
        ('drops', '0002_alter_drop_banner_image'),
        ('products', '0005_data_migration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='products.productvariant'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='drop_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='drops.dropproduct'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('drop_product__isnull', False)), fields=('cart', 'drop_product', 'color', 'size'), name='unique_cart_drop_product_variant'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('product_variant__isnull', False)), fields=('cart', 'product_variant'), name='unique_cart_product_variant'),
        ),
    ]
