# Generated by Django 5.2.1 on 2025-06-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitem_unique_together_and_more'),
        ('drops', '0002_alter_drop_banner_image'),
        ('products', '0005_data_migration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'drop_product'], name='carts_carti_cart_id_f115bd_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product_variant'], name='carts_carti_cart_id_8cc239_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['drop_product', 'color', 'size'], name='carts_carti_drop_pr_8bdb59_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['added_at'], name='carts_carti_added_a_0dfec9_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'added_at'], name='carts_carti_cart_id_b857fe_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['quantity'], name='carts_carti_quantit_763a44_idx'),
        ),
    ]
