# Generated by Django 5.2.1 on 2025-06-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cartitem_carts_carti_cart_id_f115bd_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='carts_carti_cart_id_f115bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='carts_carti_cart_id_8cc239_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='carts_carti_drop_pr_8bdb59_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='carts_carti_added_a_0dfec9_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='carts_carti_cart_id_b857fe_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='carts_carti_quantit_763a44_idx',
        ),
    ]
