# Generated by Django 5.2.1 on 2025-06-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone number')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this subscriber has been converted to a user', verbose_name='processed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
            ],
            options={
                'verbose_name': 'Waitlist Subscriber',
                'verbose_name_plural': 'Waitlist Subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
