# Generated by Django 5.2.1 on 2025-06-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_waitlistsubscriber_updates'),
        ('users', '0004_waitlistsubscriber_name_waitlistsubscriber_source_and_more'),
    ]

    operations = [
    ]
