# Generated by Django 5.2.1 on 2025-06-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20250614_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='waitlistsubscriber',
            name='source',
            field=models.CharField(choices=[('waiting_page', 'Waiting Page'), ('website', 'Website'), ('social_media', 'Social Media'), ('email_campaign', 'Email Campaign'), ('referral', 'Referral'), ('advertisement', 'Advertisement'), ('influencer', 'Influencer'), ('newsletter', 'Newsletter'), ('other', 'Other')], default='waiting_page', help_text='How the subscriber found us', max_length=50, verbose_name='source'),
        ),
    ]
